# Generated by Django 5.0.4 on 2024-10-04 11:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usermodel_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=300, validators=[django.core.validators.RegexValidator('[0-9a-zA-Z]{5,}', 'Only upper and lower case letters and numbers')]),
        ),
    ]
