# Generated by Django 5.0.4 on 2024-08-01 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_remove_contactmodel_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
