# Generated by Django 5.0.4 on 2024-06-24 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_goodsmodel_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsmodel',
            options={'ordering': ['id']},
        ),
    ]
